USE [master]
GO

/****** Object:  Database [NHibernateDemoDb]    Script Date: 08/01/2020 03:24:21 PM ******/
DROP DATABASE [NHibernateDemoDb]
GO

/****** Object:  Database [NHibernateDemoDb]    Script Date: 08/01/2020 03:24:21 PM ******/
CREATE DATABASE [NHibernateDemoDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NHibernateDemoDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\NHibernateDemoDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'NHibernateDemoDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\NHibernateDemoDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [NHibernateDemoDb] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NHibernateDemoDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [NHibernateDemoDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [NHibernateDemoDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [NHibernateDemoDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [NHibernateDemoDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [NHibernateDemoDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [NHibernateDemoDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [NHibernateDemoDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [NHibernateDemoDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [NHibernateDemoDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [NHibernateDemoDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [NHibernateDemoDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [NHibernateDemoDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [NHibernateDemoDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [NHibernateDemoDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [NHibernateDemoDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [NHibernateDemoDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [NHibernateDemoDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [NHibernateDemoDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [NHibernateDemoDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [NHibernateDemoDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [NHibernateDemoDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [NHibernateDemoDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [NHibernateDemoDb] SET RECOVERY FULL 
GO

ALTER DATABASE [NHibernateDemoDb] SET  MULTI_USER 
GO

ALTER DATABASE [NHibernateDemoDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [NHibernateDemoDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [NHibernateDemoDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [NHibernateDemoDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [NHibernateDemoDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [NHibernateDemoDb] SET QUERY_STORE = OFF
GO

USE [NHibernateDemoDb]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [NHibernateDemoDb] SET  READ_WRITE 
GO


